akai-org/wosp-puszki

.gitignore, client/.gitignore, client/src/components/ProtectedRoute/ProtectedRoute.tsx, client/tsconfig.json
Added Protected route, set up basic typedoc configuration & updated root .gitignore.
=> Adding protected route

server/.dockerignore, server/.env.example, server/.gitignore, server/Dockerfile, server/docker-compose.yml, server/docker/mysql/storage/.gitignore, server/docker/nginx/conf/site.conf, server/docker/nginx/logs/.gitignore, server/first_launch.sh, server/readme.md
It works more or less but frontend styling is broken so wip
=> Dockerize project

server/tests/Feature/FetchesDataFromNBPApiTest.php
Discussion has been resolved in Posnania just a while ago and conclusion has been drawn, that the test may remain
=> :bulb: Remove code comment discussion lol

client/src/App.tsx, client/src/components/Layout/Sidebar.module.css, client/src/components/Layout/SidebarItem.module.css, client/src/components/Layout/SidebarItem.tsx
Style selector fix and some minor changes in sidebar style to make it even more similar to the design. 
App.tsx needed a close "}" to work properly.
=> Fix style selector

server/docker/nginx/conf/site.conf
So one can enter paths other than /
=> 🔧 Allow paths in nginx config file

client/src/App.tsx, client/src/components/forms/FindBoxForm/FindBoxForm.module.less, client/src/components/forms/FindBoxForm/FindBoxForm.tsx, client/src/components/forms/FormButton/FormButton.module.less, client/src/components/forms/FormError/FormError.module.less, client/src/components/forms/FormWrapper/FormWrapper.module.less, client/src/components/forms/GiveBoxForm/GiveBoxForm.module.less, client/src/components/forms/GiveBoxForm/GiveBoxForm.tsx, client/src/components/forms/GiveBoxForm/index.ts, client/src/components/forms/index.ts, client/src/less/variables.less, client/src/pages/admin/AdminPage.module.less, client/src/pages/boxes/BoxesPage.module.less, client/src/pages/boxes/GiveBoxPage/GiveBoxPage.module.less, client/src/pages/boxes/GiveBoxPage/GiveBoxPage.tsx
Create new page "Give Box", update Form components and "Find Box" page to v1.1 mockups. Fix bug in App.tsx, which makes "margin" under every page, hot fix height of pages with table.
=> Give box page and match style with v1.1 mockup

client/src/components/Layout/InnerLayout/InnerLayout.tsx, client/src/components/Layout/InnerLayout/InnerLayoutManager/InnerLayoutManager.tsx, client/src/components/Layout/InnerLayout/InnerLayoutManager/index.ts, client/src/components/Layout/MainLayout/MainLayout.tsx, client/src/components/Layout/Sidebar/SidebarItem/SidebarItem.tsx, client/src/components/Layout/Spinner/Spinner.tsx, client/src/components/forms/FormError/FormError.module.less, client/src/components/forms/FormError/FormError.tsx, client/src/components/forms/FormWrapper/FormWrapper.module.less, client/src/components/forms/FormWrapper/FormWrapper.tsx, client/src/components/forms/GiveBoxForm/GiveBoxForm.tsx, client/src/components/forms/LoginForm/LoginForm.tsx, client/src/components/main/Main.tsx, client/src/less/variables.less, client/src/pages/MainPage/MainPage.tsx, client/src/pages/MainPage/index.ts, client/src/pages/boxes/SettleBoxPage/SettleBoxPage.module.less, client/src/pages/boxes/SettleBoxPage/SettleBoxPage.tsx, client/src/pages/boxes/index.ts, client/src/pages/home/HomePage.tsx, client/src/routes/nestedRoutes/boxesRoute.tsx, client/src/utils/APIManager.ts, client/src/utils/fetcher.ts, client/src/utils/formsErrorMessages.ts, client/src/utils/types.ts
As above. Implemented giving boxes, added succes info on form & switched login form to react-query
=> Giving boxes implemented + overall refactor

client/src/components/AcceptDataCard/AcceptDataCard.tsx, client/src/components/Layout/Sidebar/Sidebar.tsx, client/src/components/forms/FindBoxForm/FindBoxForm.tsx, client/src/components/main/Main.tsx, client/src/routes/nestedRoutes/boxesRoute.tsx
=> Hiding not implemented features

client/src/components/forms/DepositBoxForm/DepositBoxForm.module.less, client/src/components/forms/DepositBoxForm/DepositBoxForm.tsx, client/src/components/forms/DepositBoxForm/DepositContext.tsx, client/src/components/forms/DepositBoxForm/Sum.ts, client/src/components/forms/DepositFormColumn/DepositFormColumn.module.less, client/src/components/forms/DepositFormColumn/DepositFormColumn.tsx, client/src/components/forms/InputNumberBox/InputNumberBox.module.less, client/src/components/forms/InputNumberBox/InputNumberBox.tsx, client/src/pages/boxes/SettleBoxPageCheckout/SettleBoxPageCheckout.tsx
=> Deposit site

client/src/components/main/Collected.tsx, client/src/components/main/Main.tsx, client/tests/utils/testIDs.ts
I'm not sure what 'amount_total_in_PLN' returns. Is it total money from boxes that includes foreign currency?
=> Main page updated to figma design

client/src/components/boxes/DepositBox/DepositBoxForm/DepositBoxForm.tsx, client/src/pages/boxes/AcceptDataPage/AcceptDataPage.tsx, client/src/pages/boxes/SettleBoxPageCheckout/SettleBoxPageCheckout.tsx, client/src/utils/Hooks/index.ts, client/src/utils/Hooks/useGetBoxData.ts
returns non-nullable values,
if any of these values are null it navigate to the start of settle process
=> custom hook

client/public/mockServiceWorker.js, client/src/components/Layout/Navbar/Navbar.test.tsx, client/src/components/Layout/Navbar/NavbarItem.tsx, client/src/stories/NavBar.stories.tsx
=> Navbar storybook and test

client/src/components/forms/NewVolunteerForm/NewVolunteerForm.tsx, client/src/pages/admin/AddVolunteerPage/AddVolunteerPage.tsx, client/src/utils/Classes/APIManager.ts
Oddaje podpiete api, testów strony nie robilem.
Z rzeczy które zauważyłem jeszcze, że trzeba zrobić to:
- backend zwraca response 200 z typem error (nie mamy zrobionej obslugi tego typu combo)
- gdy naciśnie się przycisk bez wypełnionych inputów, inputy się trochę rozjeżdżają
=> Add volunteer collector form

client/package.json, client/src/pages/admin/ListVolunteersPage/ListVolunteersPage.tsx, client/src/utils/Functions/createRefactorData.ts, client/src/utils/queries.ts, client/src/utils/types.ts
Po prostu wyświetlenie listy wolontariuszy
=> Displaying volunteers

server/app/Collector.php, server/app/Console/Commands/ImportCollectors.php, server/app/Http/Controllers/Api/CollectorApiController.php, server/app/Http/Controllers/CollectorController.php, server/app/Http/Requests/Api/CollectorRequest.php, server/app/Virtual/Models/Collector.php, server/database/migrations/2024_01_20_141352_add_phone_number_column_to_collectors_table.php, server/resources/views/liczymy/collector/create.blade.php, server/storage/api-docs/api-docs.json
Add phone number to the collector column. This field will be set by the importer and will be displayed in API
=> Add phone number field to the collector for the API

server/app/Http/Controllers/Api/UserApiController.php
=> Add user validation for API.

client/src/components/Layout/Navbar/Navbar.test.tsx, client/src/index.css, client/src/pages/admin/LogsPage/LogsPage.tsx, client/src/pages/countedBoxes/BoxesApprovedPage/BoxesForApprovalPage.tsx, client/src/pages/countedBoxes/BoxesApprovedPage/BoxesPage.module.less, client/src/routes/nestedRoutes/countedBoxesRoute.tsx, client/src/stories/NavBar.stories.tsx, client/src/utils/CreateColumns.tsx, client/src/utils/Functions/createRefactorData.ts, client/src/utils/Functions/createUserData.ts, client/src/utils/types.ts
Puszki - lista: Pole ID zamienić na ID wolontariusza (obecnie ID puszki, zmienić też etykiete)
Puszki - lista: wiersze  powinny być niższe i węższe, żeby zwiększyć gęstość informacji
Puszki - lista: ograniczyć ilość puszek wyświetlanych na raz do 100 za pomocą opcji paginaation
Puszki - lista: zmienić kolejność kolumn: PLNy powinny być przed walutami obcymi 
Puszki - lista: przyciski modyfikuj i podgląd powinny być kolorowe i zawierać ikony
=> Tweaks to box table

client/src/components/boxes/FindBoxForm/FindBoxForm.module.less
=> Rozszerzenie pól

client/src/components/boxes/AcceptDataCard/AcceptDataCard.tsx, client/src/pages/boxes/DepositBoxPage/DepositBoxPage.tsx, client/src/pages/boxes/SettleBoxPageCheckout/SettleBoxPageCheckout.tsx
Resolves #225 
Widok wolontariusza:
=> Ukrycie wartości id puszek z bazy danych dla wolontariuszy

server/app/Http/Controllers/Api/CollectorApiController.php, server/routes/api.php, server/routes/web.php, server/tests/Feature/Api/Collector/CreateCollectorTest.php
Resolves #221 
Poprawa roli (wcześniej przekierowywało na 'liczymy' 302)
Dodanie testu
=> Fix role for collector endpoints

client/src/utils/CreateColumns.tsx
Poprawka pozwalająca na poprawny build
=> Fix 'Highlighter' cannot be used as a JSX component
